name: .NET Core

on:
  push:
    paths:
    - 'src/**'
    - 'Directory.Build.props'
    branches: [ master ]
  pull_request:
    paths:
    - 'src/**'
    - 'Directory.Build.props'
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -o artifacts --configuration Release --no-build src/PrioritySchedulingTools
